require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

# For compatibility with `:passed_2` status
Naming/VariableNumber:
  EnforcedStyle: snake_case
